apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosblade-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaosblade-operator
  template:
    metadata:
      labels:
        name: chaosblade-operator
        part-of: chaosblade
    spec:
      serviceAccountName: chaosblade
      containers:
        - name: chaosblade-operator
          image: {{ .Values.operator.repository }}:{{ .Values.operator.version }}
          command: ["chaosblade-operator"]
          args:
          {{- if .Values.blade.repository }}
          - '--chaosblade-image-repository={{ .Values.blade.repository }}'
          {{- end }}
          {{- if .Values.blade.version }}
          - '--chaosblade-version={{ .Values.blade.version }}'
          {{- end }}
          {{- if .Values.blade.pullPolicy }}
          - '--chaosblade-image-pull-policy={{ .Values.blade.pullPolicy }}'
          {{- end }}
          - '--chaosblade-namespace={{ .Release.Namespace }}'
          {{- if .Values.env.zapLevel }}
          - '--zap-level={{ .Values.env.zapLevel }}'
          {{- end }}
          {{- if eq .Value.webhook.enable "true" }}
          - '--webhook-enable'
          {{- end }}
          imagePullPolicy: {{ .Values.operator.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chaosblade-operator"
          ports:
            - containerPort: 9443
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: chaosblade-webhook-server-cert